# [[redirects]]
# force = true
# from = "/api/*"
# status = 200

# [[redirects]]
# from = '/*'
# status = 200
# to = '/index.html'


[[redirects]]
  from = "/api/*"
  to = 'https://www.wallstreetoddsapi.com/api/:splat'
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200