[[redirects]]
force = true
from = '/api'
status = 200
to = 'https://www.wallstreetoddsapi.com/api/'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'npm run build'
publish = 'dist'

[dev]
autoLaunch = false

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"